// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module canny_accel_xFCannyKernel (
        in_mat_data1_dout,
        in_mat_data1_empty_n,
        in_mat_data1_read,
        dst_mat_data2_din,
        dst_mat_data2_full_n,
        dst_mat_data2_write,
        p_lowthreshold,
        p_highthreshold,
        img_height,
        img_width,
        ap_clk,
        ap_rst,
        p_lowthreshold_ap_vld,
        p_highthreshold_ap_vld,
        ap_start,
        img_height_ap_vld,
        img_width_ap_vld,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);


input  [7:0] in_mat_data1_dout;
input   in_mat_data1_empty_n;
output   in_mat_data1_read;
output  [63:0] dst_mat_data2_din;
input   dst_mat_data2_full_n;
output   dst_mat_data2_write;
input  [7:0] p_lowthreshold;
input  [7:0] p_highthreshold;
input  [15:0] img_height;
input  [15:0] img_width;
input   ap_clk;
input   ap_rst;
input   p_lowthreshold_ap_vld;
input   p_highthreshold_ap_vld;
input   ap_start;
input   img_height_ap_vld;
input   img_width_ap_vld;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

wire    entry_proc16_U0_ap_start;
wire    entry_proc16_U0_ap_done;
wire    entry_proc16_U0_ap_continue;
wire    entry_proc16_U0_ap_idle;
wire    entry_proc16_U0_ap_ready;
wire    entry_proc16_U0_start_out;
wire    entry_proc16_U0_start_write;
wire   [7:0] entry_proc16_U0_p_lowthreshold_c_din;
wire    entry_proc16_U0_p_lowthreshold_c_write;
wire   [7:0] entry_proc16_U0_p_highthreshold_c_din;
wire    entry_proc16_U0_p_highthreshold_c_write;
wire    entry_proc16_U0_ap_ext_blocking_n;
wire    entry_proc16_U0_ap_str_blocking_n;
wire    entry_proc16_U0_ap_int_blocking_n;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_start;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_done;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_continue;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_idle;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_start_out;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_start_write;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_in_mat_data1_read;
wire   [7:0] xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_gaussian_mat_data1_din;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_gaussian_mat_data1_write;
wire   [15:0] xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_height_c22_din;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_height_c22_write;
wire   [15:0] xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_width_c26_din;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_width_c26_write;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ext_blocking_n;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_str_blocking_n;
wire    xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_int_blocking_n;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_start;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_done;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_continue;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_idle;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_ready;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_start_out;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_start_write;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gaussian_mat_data1_read;
wire   [15:0] xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gradx_mat_data2_din;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gradx_mat_data2_write;
wire   [15:0] xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_grady_mat_data5_din;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_grady_mat_data5_write;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_imgheight_read;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_imgwidth_read;
wire   [15:0] xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_height_c21_din;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_height_c21_write;
wire   [15:0] xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_width_c25_din;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_width_c25_write;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_ext_blocking_n;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_str_blocking_n;
wire    xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_int_blocking_n;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_start;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_done;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_continue;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_idle;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_ready;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_start_out;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_start_write;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx_mat_data2_read;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady_mat_data5_read;
wire   [15:0] xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx1_mat_data3_din;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx1_mat_data3_write;
wire   [15:0] xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx2_mat_data4_din;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx2_mat_data4_write;
wire   [15:0] xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady1_mat_data6_din;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady1_mat_data6_write;
wire   [15:0] xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady2_mat_data7_din;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady2_mat_data7_write;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_read;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_read;
wire   [15:0] xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_c20_din;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_c20_write;
wire   [15:0] xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_c24_din;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_c24_write;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_ext_blocking_n;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_str_blocking_n;
wire    xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_int_blocking_n;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_start;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_done;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_continue;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_idle;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_ready;
wire   [15:0] xFCannyKernel_Block_entry15_proc_U0_ap_return_0;
wire   [15:0] xFCannyKernel_Block_entry15_proc_U0_ap_return_1;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_ext_blocking_n;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_str_blocking_n;
wire    xFCannyKernel_Block_entry15_proc_U0_ap_int_blocking_n;
wire    ap_channel_done_height;
wire    height_full_n;
reg    ap_sync_reg_channel_write_height;
wire    ap_sync_channel_write_height;
wire    ap_channel_done_imgwidth;
wire    imgwidth_full_n;
reg    ap_sync_reg_channel_write_imgwidth;
wire    ap_sync_channel_write_imgwidth;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_start;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_done;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_continue;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_idle;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_ready;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_gradx1_mat_data3_read;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_grady1_mat_data6_read;
wire   [15:0] xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_magnitude_mat_data8_din;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_magnitude_mat_data8_write;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_ext_blocking_n;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_str_blocking_n;
wire    xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_int_blocking_n;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_start;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_done;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_continue;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_idle;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_ready;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_gradx2_mat_data4_read;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_grady2_mat_data7_read;
wire   [7:0] xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_phase_mat_data9_din;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_phase_mat_data9_write;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_imgheight_read;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_imgwidth_read;
wire   [15:0] xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_height_c19_din;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_height_c19_write;
wire   [15:0] xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_width_c23_din;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_width_c23_write;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_ext_blocking_n;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_str_blocking_n;
wire    xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_int_blocking_n;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_start;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_done;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_continue;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_idle;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_ready;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_start_out;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_start_write;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_magnitude_mat_data8_read;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_phase_mat_data9_read;
wire   [1:0] xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_nms_mat_data10_din;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_nms_mat_data10_write;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_low_threshold_read;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_high_threshold_read;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_imgheight_read;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_imgwidth_read;
wire   [15:0] xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_height_c_din;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_height_c_write;
wire   [15:0] xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_width_c_din;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_width_c_write;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_ext_blocking_n;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_str_blocking_n;
wire    xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_int_blocking_n;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_start;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_done;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_continue;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_idle;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_ready;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_nms_mat_data10_read;
wire   [63:0] xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dst_mat_data2_din;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dst_mat_data2_write;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_imgheight_read;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_imgwidth_read;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_ext_blocking_n;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_str_blocking_n;
wire    xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_int_blocking_n;
wire    p_lowthreshold_c_full_n;
wire   [7:0] p_lowthreshold_c_dout;
wire   [3:0] p_lowthreshold_c_num_data_valid;
wire   [3:0] p_lowthreshold_c_fifo_cap;
wire    p_lowthreshold_c_empty_n;
wire    p_highthreshold_c_full_n;
wire   [7:0] p_highthreshold_c_dout;
wire   [3:0] p_highthreshold_c_num_data_valid;
wire   [3:0] p_highthreshold_c_fifo_cap;
wire    p_highthreshold_c_empty_n;
wire    gaussian_mat_data_full_n;
wire   [7:0] gaussian_mat_data_dout;
wire   [1:0] gaussian_mat_data_num_data_valid;
wire   [1:0] gaussian_mat_data_fifo_cap;
wire    gaussian_mat_data_empty_n;
wire    img_height_c22_full_n;
wire   [15:0] img_height_c22_dout;
wire   [1:0] img_height_c22_num_data_valid;
wire   [1:0] img_height_c22_fifo_cap;
wire    img_height_c22_empty_n;
wire    img_width_c26_full_n;
wire   [15:0] img_width_c26_dout;
wire   [1:0] img_width_c26_num_data_valid;
wire   [1:0] img_width_c26_fifo_cap;
wire    img_width_c26_empty_n;
wire    gradx_mat_data_full_n;
wire   [15:0] gradx_mat_data_dout;
wire   [1:0] gradx_mat_data_num_data_valid;
wire   [1:0] gradx_mat_data_fifo_cap;
wire    gradx_mat_data_empty_n;
wire    grady_mat_data_full_n;
wire   [15:0] grady_mat_data_dout;
wire   [1:0] grady_mat_data_num_data_valid;
wire   [1:0] grady_mat_data_fifo_cap;
wire    grady_mat_data_empty_n;
wire    img_height_c21_full_n;
wire   [15:0] img_height_c21_dout;
wire   [1:0] img_height_c21_num_data_valid;
wire   [1:0] img_height_c21_fifo_cap;
wire    img_height_c21_empty_n;
wire    img_width_c25_full_n;
wire   [15:0] img_width_c25_dout;
wire   [1:0] img_width_c25_num_data_valid;
wire   [1:0] img_width_c25_fifo_cap;
wire    img_width_c25_empty_n;
wire    gradx1_mat_data_full_n;
wire   [15:0] gradx1_mat_data_dout;
wire   [1:0] gradx1_mat_data_num_data_valid;
wire   [1:0] gradx1_mat_data_fifo_cap;
wire    gradx1_mat_data_empty_n;
wire    gradx2_mat_data_full_n;
wire   [15:0] gradx2_mat_data_dout;
wire   [1:0] gradx2_mat_data_num_data_valid;
wire   [1:0] gradx2_mat_data_fifo_cap;
wire    gradx2_mat_data_empty_n;
wire    grady1_mat_data_full_n;
wire   [15:0] grady1_mat_data_dout;
wire   [1:0] grady1_mat_data_num_data_valid;
wire   [1:0] grady1_mat_data_fifo_cap;
wire    grady1_mat_data_empty_n;
wire    grady2_mat_data_full_n;
wire   [15:0] grady2_mat_data_dout;
wire   [1:0] grady2_mat_data_num_data_valid;
wire   [1:0] grady2_mat_data_fifo_cap;
wire    grady2_mat_data_empty_n;
wire    img_height_c20_full_n;
wire   [15:0] img_height_c20_dout;
wire   [1:0] img_height_c20_num_data_valid;
wire   [1:0] img_height_c20_fifo_cap;
wire    img_height_c20_empty_n;
wire    img_width_c24_full_n;
wire   [15:0] img_width_c24_dout;
wire   [1:0] img_width_c24_num_data_valid;
wire   [1:0] img_width_c24_fifo_cap;
wire    img_width_c24_empty_n;
wire   [15:0] imgwidth_dout;
wire   [2:0] imgwidth_num_data_valid;
wire   [2:0] imgwidth_fifo_cap;
wire    imgwidth_empty_n;
wire   [15:0] height_dout;
wire   [2:0] height_num_data_valid;
wire   [2:0] height_fifo_cap;
wire    height_empty_n;
wire    magnitude_mat_data_full_n;
wire   [15:0] magnitude_mat_data_dout;
wire   [1:0] magnitude_mat_data_num_data_valid;
wire   [1:0] magnitude_mat_data_fifo_cap;
wire    magnitude_mat_data_empty_n;
wire    phase_mat_data_full_n;
wire   [7:0] phase_mat_data_dout;
wire   [13:0] phase_mat_data_num_data_valid;
wire   [13:0] phase_mat_data_fifo_cap;
wire    phase_mat_data_empty_n;
wire    img_height_c19_full_n;
wire   [15:0] img_height_c19_dout;
wire   [1:0] img_height_c19_num_data_valid;
wire   [1:0] img_height_c19_fifo_cap;
wire    img_height_c19_empty_n;
wire    img_width_c23_full_n;
wire   [15:0] img_width_c23_dout;
wire   [1:0] img_width_c23_num_data_valid;
wire   [1:0] img_width_c23_fifo_cap;
wire    img_width_c23_empty_n;
wire    nms_mat_data_full_n;
wire   [1:0] nms_mat_data_dout;
wire   [1:0] nms_mat_data_num_data_valid;
wire   [1:0] nms_mat_data_fifo_cap;
wire    nms_mat_data_empty_n;
wire    img_height_c_full_n;
wire   [15:0] img_height_c_dout;
wire   [1:0] img_height_c_num_data_valid;
wire   [1:0] img_height_c_fifo_cap;
wire    img_height_c_empty_n;
wire    img_width_c_full_n;
wire   [15:0] img_width_c_dout;
wire   [1:0] img_width_c_num_data_valid;
wire   [1:0] img_width_c_fifo_cap;
wire    img_width_c_empty_n;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc16_U0_ap_ready;
wire    ap_sync_entry_proc16_U0_ap_ready;
reg    ap_sync_reg_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready;
wire    ap_sync_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready;
reg    ap_sync_reg_xFCannyKernel_Block_entry15_proc_U0_ap_ready;
wire    ap_sync_xFCannyKernel_Block_entry15_proc_U0_ap_ready;
wire   [0:0] start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_din;
wire    start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_full_n;
wire   [0:0] start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_dout;
wire    start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_empty_n;
wire   [0:0] start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_din;
wire    start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_full_n;
wire   [0:0] start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_dout;
wire    start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_empty_n;
wire   [0:0] start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_din;
wire    start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_full_n;
wire   [0:0] start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_dout;
wire    start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_empty_n;
wire   [0:0] start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_din;
wire    start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_full_n;
wire   [0:0] start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_dout;
wire    start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_empty_n;
wire   [0:0] start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_din;
wire    start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_full_n;
wire   [0:0] start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dout;
wire    start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_empty_n;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_height = 1'b0;
#0 ap_sync_reg_channel_write_imgwidth = 1'b0;
#0 ap_sync_reg_entry_proc16_U0_ap_ready = 1'b0;
#0 ap_sync_reg_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready = 1'b0;
#0 ap_sync_reg_xFCannyKernel_Block_entry15_proc_U0_ap_ready = 1'b0;
end

canny_accel_entry_proc16 entry_proc16_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(entry_proc16_U0_ap_start),
    .start_full_n(start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_full_n),
    .ap_done(entry_proc16_U0_ap_done),
    .ap_continue(entry_proc16_U0_ap_continue),
    .ap_idle(entry_proc16_U0_ap_idle),
    .ap_ready(entry_proc16_U0_ap_ready),
    .start_out(entry_proc16_U0_start_out),
    .start_write(entry_proc16_U0_start_write),
    .p_lowthreshold(p_lowthreshold),
    .p_lowthreshold_c_din(entry_proc16_U0_p_lowthreshold_c_din),
    .p_lowthreshold_c_num_data_valid(p_lowthreshold_c_num_data_valid),
    .p_lowthreshold_c_fifo_cap(p_lowthreshold_c_fifo_cap),
    .p_lowthreshold_c_full_n(p_lowthreshold_c_full_n),
    .p_lowthreshold_c_write(entry_proc16_U0_p_lowthreshold_c_write),
    .p_highthreshold(p_highthreshold),
    .p_highthreshold_c_din(entry_proc16_U0_p_highthreshold_c_din),
    .p_highthreshold_c_num_data_valid(p_highthreshold_c_num_data_valid),
    .p_highthreshold_c_fifo_cap(p_highthreshold_c_fifo_cap),
    .p_highthreshold_c_full_n(p_highthreshold_c_full_n),
    .p_highthreshold_c_write(entry_proc16_U0_p_highthreshold_c_write),
    .ap_ext_blocking_n(entry_proc16_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(entry_proc16_U0_ap_str_blocking_n),
    .ap_int_blocking_n(entry_proc16_U0_ap_int_blocking_n)
);

canny_accel_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_s xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_start),
    .start_full_n(start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_full_n),
    .ap_done(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_done),
    .ap_continue(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_continue),
    .ap_idle(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_idle),
    .ap_ready(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready),
    .start_out(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_start_out),
    .start_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_start_write),
    .in_mat_data1_dout(in_mat_data1_dout),
    .in_mat_data1_num_data_valid(2'd0),
    .in_mat_data1_fifo_cap(2'd0),
    .in_mat_data1_empty_n(in_mat_data1_empty_n),
    .in_mat_data1_read(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_in_mat_data1_read),
    .gaussian_mat_data1_din(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_gaussian_mat_data1_din),
    .gaussian_mat_data1_num_data_valid(gaussian_mat_data_num_data_valid),
    .gaussian_mat_data1_fifo_cap(gaussian_mat_data_fifo_cap),
    .gaussian_mat_data1_full_n(gaussian_mat_data_full_n),
    .gaussian_mat_data1_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_gaussian_mat_data1_write),
    .img_height(img_height),
    .img_width(img_width),
    .img_height_c22_din(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_height_c22_din),
    .img_height_c22_num_data_valid(img_height_c22_num_data_valid),
    .img_height_c22_fifo_cap(img_height_c22_fifo_cap),
    .img_height_c22_full_n(img_height_c22_full_n),
    .img_height_c22_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_height_c22_write),
    .img_width_c26_din(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_width_c26_din),
    .img_width_c26_num_data_valid(img_width_c26_num_data_valid),
    .img_width_c26_fifo_cap(img_width_c26_fifo_cap),
    .img_width_c26_full_n(img_width_c26_full_n),
    .img_width_c26_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_width_c26_write),
    .ap_ext_blocking_n(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_int_blocking_n)
);

canny_accel_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_s xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_start),
    .start_full_n(start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_full_n),
    .ap_done(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_done),
    .ap_continue(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_continue),
    .ap_idle(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_idle),
    .ap_ready(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_ready),
    .start_out(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_start_out),
    .start_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_start_write),
    .gaussian_mat_data1_dout(gaussian_mat_data_dout),
    .gaussian_mat_data1_num_data_valid(gaussian_mat_data_num_data_valid),
    .gaussian_mat_data1_fifo_cap(gaussian_mat_data_fifo_cap),
    .gaussian_mat_data1_empty_n(gaussian_mat_data_empty_n),
    .gaussian_mat_data1_read(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gaussian_mat_data1_read),
    .gradx_mat_data2_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gradx_mat_data2_din),
    .gradx_mat_data2_num_data_valid(gradx_mat_data_num_data_valid),
    .gradx_mat_data2_fifo_cap(gradx_mat_data_fifo_cap),
    .gradx_mat_data2_full_n(gradx_mat_data_full_n),
    .gradx_mat_data2_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gradx_mat_data2_write),
    .grady_mat_data5_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_grady_mat_data5_din),
    .grady_mat_data5_num_data_valid(grady_mat_data_num_data_valid),
    .grady_mat_data5_fifo_cap(grady_mat_data_fifo_cap),
    .grady_mat_data5_full_n(grady_mat_data_full_n),
    .grady_mat_data5_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_grady_mat_data5_write),
    .imgheight_dout(img_height_c22_dout),
    .imgheight_num_data_valid(img_height_c22_num_data_valid),
    .imgheight_fifo_cap(img_height_c22_fifo_cap),
    .imgheight_empty_n(img_height_c22_empty_n),
    .imgheight_read(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_imgheight_read),
    .imgwidth_dout(img_width_c26_dout),
    .imgwidth_num_data_valid(img_width_c26_num_data_valid),
    .imgwidth_fifo_cap(img_width_c26_fifo_cap),
    .imgwidth_empty_n(img_width_c26_empty_n),
    .imgwidth_read(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_imgwidth_read),
    .img_height_c21_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_height_c21_din),
    .img_height_c21_num_data_valid(img_height_c21_num_data_valid),
    .img_height_c21_fifo_cap(img_height_c21_fifo_cap),
    .img_height_c21_full_n(img_height_c21_full_n),
    .img_height_c21_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_height_c21_write),
    .img_width_c25_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_width_c25_din),
    .img_width_c25_num_data_valid(img_width_c25_num_data_valid),
    .img_width_c25_fifo_cap(img_width_c25_fifo_cap),
    .img_width_c25_full_n(img_width_c25_full_n),
    .img_width_c25_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_width_c25_write),
    .ap_ext_blocking_n(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_int_blocking_n)
);

canny_accel_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_s xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_start),
    .start_full_n(start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_full_n),
    .ap_done(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_done),
    .ap_continue(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_continue),
    .ap_idle(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_idle),
    .ap_ready(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_ready),
    .start_out(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_start_out),
    .start_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_start_write),
    .gradx_mat_data2_dout(gradx_mat_data_dout),
    .gradx_mat_data2_num_data_valid(gradx_mat_data_num_data_valid),
    .gradx_mat_data2_fifo_cap(gradx_mat_data_fifo_cap),
    .gradx_mat_data2_empty_n(gradx_mat_data_empty_n),
    .gradx_mat_data2_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx_mat_data2_read),
    .grady_mat_data5_dout(grady_mat_data_dout),
    .grady_mat_data5_num_data_valid(grady_mat_data_num_data_valid),
    .grady_mat_data5_fifo_cap(grady_mat_data_fifo_cap),
    .grady_mat_data5_empty_n(grady_mat_data_empty_n),
    .grady_mat_data5_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady_mat_data5_read),
    .gradx1_mat_data3_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx1_mat_data3_din),
    .gradx1_mat_data3_num_data_valid(gradx1_mat_data_num_data_valid),
    .gradx1_mat_data3_fifo_cap(gradx1_mat_data_fifo_cap),
    .gradx1_mat_data3_full_n(gradx1_mat_data_full_n),
    .gradx1_mat_data3_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx1_mat_data3_write),
    .gradx2_mat_data4_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx2_mat_data4_din),
    .gradx2_mat_data4_num_data_valid(gradx2_mat_data_num_data_valid),
    .gradx2_mat_data4_fifo_cap(gradx2_mat_data_fifo_cap),
    .gradx2_mat_data4_full_n(gradx2_mat_data_full_n),
    .gradx2_mat_data4_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx2_mat_data4_write),
    .grady1_mat_data6_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady1_mat_data6_din),
    .grady1_mat_data6_num_data_valid(grady1_mat_data_num_data_valid),
    .grady1_mat_data6_fifo_cap(grady1_mat_data_fifo_cap),
    .grady1_mat_data6_full_n(grady1_mat_data_full_n),
    .grady1_mat_data6_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady1_mat_data6_write),
    .grady2_mat_data7_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady2_mat_data7_din),
    .grady2_mat_data7_num_data_valid(grady2_mat_data_num_data_valid),
    .grady2_mat_data7_fifo_cap(grady2_mat_data_fifo_cap),
    .grady2_mat_data7_full_n(grady2_mat_data_full_n),
    .grady2_mat_data7_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady2_mat_data7_write),
    .img_height_dout(img_height_c21_dout),
    .img_height_num_data_valid(img_height_c21_num_data_valid),
    .img_height_fifo_cap(img_height_c21_fifo_cap),
    .img_height_empty_n(img_height_c21_empty_n),
    .img_height_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_read),
    .img_width_dout(img_width_c25_dout),
    .img_width_num_data_valid(img_width_c25_num_data_valid),
    .img_width_fifo_cap(img_width_c25_fifo_cap),
    .img_width_empty_n(img_width_c25_empty_n),
    .img_width_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_read),
    .img_height_c20_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_c20_din),
    .img_height_c20_num_data_valid(img_height_c20_num_data_valid),
    .img_height_c20_fifo_cap(img_height_c20_fifo_cap),
    .img_height_c20_full_n(img_height_c20_full_n),
    .img_height_c20_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_c20_write),
    .img_width_c24_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_c24_din),
    .img_width_c24_num_data_valid(img_width_c24_num_data_valid),
    .img_width_c24_fifo_cap(img_width_c24_fifo_cap),
    .img_width_c24_full_n(img_width_c24_full_n),
    .img_width_c24_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_c24_write),
    .ap_ext_blocking_n(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_int_blocking_n)
);

canny_accel_xFCannyKernel_Block_entry15_proc xFCannyKernel_Block_entry15_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFCannyKernel_Block_entry15_proc_U0_ap_start),
    .ap_done(xFCannyKernel_Block_entry15_proc_U0_ap_done),
    .ap_continue(xFCannyKernel_Block_entry15_proc_U0_ap_continue),
    .ap_idle(xFCannyKernel_Block_entry15_proc_U0_ap_idle),
    .ap_ready(xFCannyKernel_Block_entry15_proc_U0_ap_ready),
    .img_width(img_width),
    .img_height(img_height),
    .ap_return_0(xFCannyKernel_Block_entry15_proc_U0_ap_return_0),
    .ap_return_1(xFCannyKernel_Block_entry15_proc_U0_ap_return_1),
    .ap_ext_blocking_n(xFCannyKernel_Block_entry15_proc_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFCannyKernel_Block_entry15_proc_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFCannyKernel_Block_entry15_proc_U0_ap_int_blocking_n)
);

canny_accel_xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_s xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_start),
    .ap_done(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_done),
    .ap_continue(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_continue),
    .ap_idle(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_idle),
    .ap_ready(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_ready),
    .gradx1_mat_data3_dout(gradx1_mat_data_dout),
    .gradx1_mat_data3_num_data_valid(gradx1_mat_data_num_data_valid),
    .gradx1_mat_data3_fifo_cap(gradx1_mat_data_fifo_cap),
    .gradx1_mat_data3_empty_n(gradx1_mat_data_empty_n),
    .gradx1_mat_data3_read(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_gradx1_mat_data3_read),
    .grady1_mat_data6_dout(grady1_mat_data_dout),
    .grady1_mat_data6_num_data_valid(grady1_mat_data_num_data_valid),
    .grady1_mat_data6_fifo_cap(grady1_mat_data_fifo_cap),
    .grady1_mat_data6_empty_n(grady1_mat_data_empty_n),
    .grady1_mat_data6_read(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_grady1_mat_data6_read),
    .magnitude_mat_data8_din(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_magnitude_mat_data8_din),
    .magnitude_mat_data8_num_data_valid(magnitude_mat_data_num_data_valid),
    .magnitude_mat_data8_fifo_cap(magnitude_mat_data_fifo_cap),
    .magnitude_mat_data8_full_n(magnitude_mat_data_full_n),
    .magnitude_mat_data8_write(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_magnitude_mat_data8_write),
    .p_read(height_dout),
    .p_read1(imgwidth_dout),
    .ap_ext_blocking_n(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_int_blocking_n)
);

canny_accel_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_s xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_start),
    .ap_done(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_done),
    .ap_continue(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_continue),
    .ap_idle(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_idle),
    .ap_ready(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_ready),
    .gradx2_mat_data4_dout(gradx2_mat_data_dout),
    .gradx2_mat_data4_num_data_valid(gradx2_mat_data_num_data_valid),
    .gradx2_mat_data4_fifo_cap(gradx2_mat_data_fifo_cap),
    .gradx2_mat_data4_empty_n(gradx2_mat_data_empty_n),
    .gradx2_mat_data4_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_gradx2_mat_data4_read),
    .grady2_mat_data7_dout(grady2_mat_data_dout),
    .grady2_mat_data7_num_data_valid(grady2_mat_data_num_data_valid),
    .grady2_mat_data7_fifo_cap(grady2_mat_data_fifo_cap),
    .grady2_mat_data7_empty_n(grady2_mat_data_empty_n),
    .grady2_mat_data7_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_grady2_mat_data7_read),
    .phase_mat_data9_din(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_phase_mat_data9_din),
    .phase_mat_data9_num_data_valid(phase_mat_data_num_data_valid),
    .phase_mat_data9_fifo_cap(phase_mat_data_fifo_cap),
    .phase_mat_data9_full_n(phase_mat_data_full_n),
    .phase_mat_data9_write(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_phase_mat_data9_write),
    .imgheight_dout(img_height_c20_dout),
    .imgheight_num_data_valid(img_height_c20_num_data_valid),
    .imgheight_fifo_cap(img_height_c20_fifo_cap),
    .imgheight_empty_n(img_height_c20_empty_n),
    .imgheight_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_imgheight_read),
    .imgwidth_dout(img_width_c24_dout),
    .imgwidth_num_data_valid(img_width_c24_num_data_valid),
    .imgwidth_fifo_cap(img_width_c24_fifo_cap),
    .imgwidth_empty_n(img_width_c24_empty_n),
    .imgwidth_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_imgwidth_read),
    .img_height_c19_din(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_height_c19_din),
    .img_height_c19_num_data_valid(img_height_c19_num_data_valid),
    .img_height_c19_fifo_cap(img_height_c19_fifo_cap),
    .img_height_c19_full_n(img_height_c19_full_n),
    .img_height_c19_write(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_height_c19_write),
    .img_width_c23_din(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_width_c23_din),
    .img_width_c23_num_data_valid(img_width_c23_num_data_valid),
    .img_width_c23_fifo_cap(img_width_c23_fifo_cap),
    .img_width_c23_full_n(img_width_c23_full_n),
    .img_width_c23_write(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_width_c23_write),
    .ap_ext_blocking_n(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_int_blocking_n)
);

canny_accel_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_s xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_start),
    .start_full_n(start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_full_n),
    .ap_done(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_done),
    .ap_continue(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_continue),
    .ap_idle(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_idle),
    .ap_ready(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_ready),
    .start_out(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_start_out),
    .start_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_start_write),
    .magnitude_mat_data8_dout(magnitude_mat_data_dout),
    .magnitude_mat_data8_num_data_valid(magnitude_mat_data_num_data_valid),
    .magnitude_mat_data8_fifo_cap(magnitude_mat_data_fifo_cap),
    .magnitude_mat_data8_empty_n(magnitude_mat_data_empty_n),
    .magnitude_mat_data8_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_magnitude_mat_data8_read),
    .phase_mat_data9_dout(phase_mat_data_dout),
    .phase_mat_data9_num_data_valid(phase_mat_data_num_data_valid),
    .phase_mat_data9_fifo_cap(phase_mat_data_fifo_cap),
    .phase_mat_data9_empty_n(phase_mat_data_empty_n),
    .phase_mat_data9_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_phase_mat_data9_read),
    .nms_mat_data10_din(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_nms_mat_data10_din),
    .nms_mat_data10_num_data_valid(nms_mat_data_num_data_valid),
    .nms_mat_data10_fifo_cap(nms_mat_data_fifo_cap),
    .nms_mat_data10_full_n(nms_mat_data_full_n),
    .nms_mat_data10_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_nms_mat_data10_write),
    .low_threshold_dout(p_lowthreshold_c_dout),
    .low_threshold_num_data_valid(p_lowthreshold_c_num_data_valid),
    .low_threshold_fifo_cap(p_lowthreshold_c_fifo_cap),
    .low_threshold_empty_n(p_lowthreshold_c_empty_n),
    .low_threshold_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_low_threshold_read),
    .high_threshold_dout(p_highthreshold_c_dout),
    .high_threshold_num_data_valid(p_highthreshold_c_num_data_valid),
    .high_threshold_fifo_cap(p_highthreshold_c_fifo_cap),
    .high_threshold_empty_n(p_highthreshold_c_empty_n),
    .high_threshold_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_high_threshold_read),
    .imgheight_dout(img_height_c19_dout),
    .imgheight_num_data_valid(img_height_c19_num_data_valid),
    .imgheight_fifo_cap(img_height_c19_fifo_cap),
    .imgheight_empty_n(img_height_c19_empty_n),
    .imgheight_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_imgheight_read),
    .imgwidth_dout(img_width_c23_dout),
    .imgwidth_num_data_valid(img_width_c23_num_data_valid),
    .imgwidth_fifo_cap(img_width_c23_fifo_cap),
    .imgwidth_empty_n(img_width_c23_empty_n),
    .imgwidth_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_imgwidth_read),
    .img_height_c_din(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_height_c_din),
    .img_height_c_num_data_valid(img_height_c_num_data_valid),
    .img_height_c_fifo_cap(img_height_c_fifo_cap),
    .img_height_c_full_n(img_height_c_full_n),
    .img_height_c_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_height_c_write),
    .img_width_c_din(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_width_c_din),
    .img_width_c_num_data_valid(img_width_c_num_data_valid),
    .img_width_c_fifo_cap(img_width_c_fifo_cap),
    .img_width_c_full_n(img_width_c_full_n),
    .img_width_c_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_width_c_write),
    .ap_ext_blocking_n(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_int_blocking_n)
);

canny_accel_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_s xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_start),
    .ap_done(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_done),
    .ap_continue(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_continue),
    .ap_idle(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_idle),
    .ap_ready(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_ready),
    .nms_mat_data10_dout(nms_mat_data_dout),
    .nms_mat_data10_num_data_valid(nms_mat_data_num_data_valid),
    .nms_mat_data10_fifo_cap(nms_mat_data_fifo_cap),
    .nms_mat_data10_empty_n(nms_mat_data_empty_n),
    .nms_mat_data10_read(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_nms_mat_data10_read),
    .dst_mat_data2_din(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dst_mat_data2_din),
    .dst_mat_data2_num_data_valid(2'd0),
    .dst_mat_data2_fifo_cap(2'd0),
    .dst_mat_data2_full_n(dst_mat_data2_full_n),
    .dst_mat_data2_write(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dst_mat_data2_write),
    .imgheight_dout(img_height_c_dout),
    .imgheight_num_data_valid(img_height_c_num_data_valid),
    .imgheight_fifo_cap(img_height_c_fifo_cap),
    .imgheight_empty_n(img_height_c_empty_n),
    .imgheight_read(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_imgheight_read),
    .imgwidth_dout(img_width_c_dout),
    .imgwidth_num_data_valid(img_width_c_num_data_valid),
    .imgwidth_fifo_cap(img_width_c_fifo_cap),
    .imgwidth_empty_n(img_width_c_empty_n),
    .imgwidth_read(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_imgwidth_read),
    .ap_ext_blocking_n(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_str_blocking_n),
    .ap_int_blocking_n(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_int_blocking_n)
);

canny_accel_fifo_w8_d6_S p_lowthreshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc16_U0_p_lowthreshold_c_din),
    .if_full_n(p_lowthreshold_c_full_n),
    .if_write(entry_proc16_U0_p_lowthreshold_c_write),
    .if_dout(p_lowthreshold_c_dout),
    .if_num_data_valid(p_lowthreshold_c_num_data_valid),
    .if_fifo_cap(p_lowthreshold_c_fifo_cap),
    .if_empty_n(p_lowthreshold_c_empty_n),
    .if_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_low_threshold_read)
);

canny_accel_fifo_w8_d6_S p_highthreshold_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc16_U0_p_highthreshold_c_din),
    .if_full_n(p_highthreshold_c_full_n),
    .if_write(entry_proc16_U0_p_highthreshold_c_write),
    .if_dout(p_highthreshold_c_dout),
    .if_num_data_valid(p_highthreshold_c_num_data_valid),
    .if_fifo_cap(p_highthreshold_c_fifo_cap),
    .if_empty_n(p_highthreshold_c_empty_n),
    .if_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_high_threshold_read)
);

canny_accel_fifo_w8_d2_S gaussian_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_gaussian_mat_data1_din),
    .if_full_n(gaussian_mat_data_full_n),
    .if_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_gaussian_mat_data1_write),
    .if_dout(gaussian_mat_data_dout),
    .if_num_data_valid(gaussian_mat_data_num_data_valid),
    .if_fifo_cap(gaussian_mat_data_fifo_cap),
    .if_empty_n(gaussian_mat_data_empty_n),
    .if_read(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gaussian_mat_data1_read)
);

canny_accel_fifo_w16_d2_S img_height_c22_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_height_c22_din),
    .if_full_n(img_height_c22_full_n),
    .if_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_height_c22_write),
    .if_dout(img_height_c22_dout),
    .if_num_data_valid(img_height_c22_num_data_valid),
    .if_fifo_cap(img_height_c22_fifo_cap),
    .if_empty_n(img_height_c22_empty_n),
    .if_read(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_imgheight_read)
);

canny_accel_fifo_w16_d2_S img_width_c26_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_width_c26_din),
    .if_full_n(img_width_c26_full_n),
    .if_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_img_width_c26_write),
    .if_dout(img_width_c26_dout),
    .if_num_data_valid(img_width_c26_num_data_valid),
    .if_fifo_cap(img_width_c26_fifo_cap),
    .if_empty_n(img_width_c26_empty_n),
    .if_read(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_imgwidth_read)
);

canny_accel_fifo_w16_d2_S gradx_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gradx_mat_data2_din),
    .if_full_n(gradx_mat_data_full_n),
    .if_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_gradx_mat_data2_write),
    .if_dout(gradx_mat_data_dout),
    .if_num_data_valid(gradx_mat_data_num_data_valid),
    .if_fifo_cap(gradx_mat_data_fifo_cap),
    .if_empty_n(gradx_mat_data_empty_n),
    .if_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx_mat_data2_read)
);

canny_accel_fifo_w16_d2_S grady_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_grady_mat_data5_din),
    .if_full_n(grady_mat_data_full_n),
    .if_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_grady_mat_data5_write),
    .if_dout(grady_mat_data_dout),
    .if_num_data_valid(grady_mat_data_num_data_valid),
    .if_fifo_cap(grady_mat_data_fifo_cap),
    .if_empty_n(grady_mat_data_empty_n),
    .if_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady_mat_data5_read)
);

canny_accel_fifo_w16_d2_S img_height_c21_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_height_c21_din),
    .if_full_n(img_height_c21_full_n),
    .if_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_height_c21_write),
    .if_dout(img_height_c21_dout),
    .if_num_data_valid(img_height_c21_num_data_valid),
    .if_fifo_cap(img_height_c21_fifo_cap),
    .if_empty_n(img_height_c21_empty_n),
    .if_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_read)
);

canny_accel_fifo_w16_d2_S img_width_c25_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_width_c25_din),
    .if_full_n(img_width_c25_full_n),
    .if_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_img_width_c25_write),
    .if_dout(img_width_c25_dout),
    .if_num_data_valid(img_width_c25_num_data_valid),
    .if_fifo_cap(img_width_c25_fifo_cap),
    .if_empty_n(img_width_c25_empty_n),
    .if_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_read)
);

canny_accel_fifo_w16_d2_S gradx1_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx1_mat_data3_din),
    .if_full_n(gradx1_mat_data_full_n),
    .if_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx1_mat_data3_write),
    .if_dout(gradx1_mat_data_dout),
    .if_num_data_valid(gradx1_mat_data_num_data_valid),
    .if_fifo_cap(gradx1_mat_data_fifo_cap),
    .if_empty_n(gradx1_mat_data_empty_n),
    .if_read(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_gradx1_mat_data3_read)
);

canny_accel_fifo_w16_d2_S gradx2_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx2_mat_data4_din),
    .if_full_n(gradx2_mat_data_full_n),
    .if_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_gradx2_mat_data4_write),
    .if_dout(gradx2_mat_data_dout),
    .if_num_data_valid(gradx2_mat_data_num_data_valid),
    .if_fifo_cap(gradx2_mat_data_fifo_cap),
    .if_empty_n(gradx2_mat_data_empty_n),
    .if_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_gradx2_mat_data4_read)
);

canny_accel_fifo_w16_d2_S grady1_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady1_mat_data6_din),
    .if_full_n(grady1_mat_data_full_n),
    .if_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady1_mat_data6_write),
    .if_dout(grady1_mat_data_dout),
    .if_num_data_valid(grady1_mat_data_num_data_valid),
    .if_fifo_cap(grady1_mat_data_fifo_cap),
    .if_empty_n(grady1_mat_data_empty_n),
    .if_read(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_grady1_mat_data6_read)
);

canny_accel_fifo_w16_d2_S grady2_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady2_mat_data7_din),
    .if_full_n(grady2_mat_data_full_n),
    .if_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_grady2_mat_data7_write),
    .if_dout(grady2_mat_data_dout),
    .if_num_data_valid(grady2_mat_data_num_data_valid),
    .if_fifo_cap(grady2_mat_data_fifo_cap),
    .if_empty_n(grady2_mat_data_empty_n),
    .if_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_grady2_mat_data7_read)
);

canny_accel_fifo_w16_d2_S img_height_c20_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_c20_din),
    .if_full_n(img_height_c20_full_n),
    .if_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_height_c20_write),
    .if_dout(img_height_c20_dout),
    .if_num_data_valid(img_height_c20_num_data_valid),
    .if_fifo_cap(img_height_c20_fifo_cap),
    .if_empty_n(img_height_c20_empty_n),
    .if_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_imgheight_read)
);

canny_accel_fifo_w16_d2_S img_width_c24_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_c24_din),
    .if_full_n(img_width_c24_full_n),
    .if_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_img_width_c24_write),
    .if_dout(img_width_c24_dout),
    .if_num_data_valid(img_width_c24_num_data_valid),
    .if_fifo_cap(img_width_c24_fifo_cap),
    .if_empty_n(img_width_c24_empty_n),
    .if_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_imgwidth_read)
);

canny_accel_fifo_w16_d4_S imgwidth_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCannyKernel_Block_entry15_proc_U0_ap_return_0),
    .if_full_n(imgwidth_full_n),
    .if_write(ap_channel_done_imgwidth),
    .if_dout(imgwidth_dout),
    .if_num_data_valid(imgwidth_num_data_valid),
    .if_fifo_cap(imgwidth_fifo_cap),
    .if_empty_n(imgwidth_empty_n),
    .if_read(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_ready)
);

canny_accel_fifo_w16_d4_S height_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFCannyKernel_Block_entry15_proc_U0_ap_return_1),
    .if_full_n(height_full_n),
    .if_write(ap_channel_done_height),
    .if_dout(height_dout),
    .if_num_data_valid(height_num_data_valid),
    .if_fifo_cap(height_fifo_cap),
    .if_empty_n(height_empty_n),
    .if_read(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_ready)
);

canny_accel_fifo_w16_d2_S magnitude_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_magnitude_mat_data8_din),
    .if_full_n(magnitude_mat_data_full_n),
    .if_write(xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_magnitude_mat_data8_write),
    .if_dout(magnitude_mat_data_dout),
    .if_num_data_valid(magnitude_mat_data_num_data_valid),
    .if_fifo_cap(magnitude_mat_data_fifo_cap),
    .if_empty_n(magnitude_mat_data_empty_n),
    .if_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_magnitude_mat_data8_read)
);

canny_accel_fifo_w8_d5760_A phase_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_phase_mat_data9_din),
    .if_full_n(phase_mat_data_full_n),
    .if_write(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_phase_mat_data9_write),
    .if_dout(phase_mat_data_dout),
    .if_num_data_valid(phase_mat_data_num_data_valid),
    .if_fifo_cap(phase_mat_data_fifo_cap),
    .if_empty_n(phase_mat_data_empty_n),
    .if_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_phase_mat_data9_read)
);

canny_accel_fifo_w16_d2_S img_height_c19_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_height_c19_din),
    .if_full_n(img_height_c19_full_n),
    .if_write(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_height_c19_write),
    .if_dout(img_height_c19_dout),
    .if_num_data_valid(img_height_c19_num_data_valid),
    .if_fifo_cap(img_height_c19_fifo_cap),
    .if_empty_n(img_height_c19_empty_n),
    .if_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_imgheight_read)
);

canny_accel_fifo_w16_d2_S img_width_c23_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_width_c23_din),
    .if_full_n(img_width_c23_full_n),
    .if_write(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_img_width_c23_write),
    .if_dout(img_width_c23_dout),
    .if_num_data_valid(img_width_c23_num_data_valid),
    .if_fifo_cap(img_width_c23_fifo_cap),
    .if_empty_n(img_width_c23_empty_n),
    .if_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_imgwidth_read)
);

canny_accel_fifo_w2_d2_S nms_mat_data_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_nms_mat_data10_din),
    .if_full_n(nms_mat_data_full_n),
    .if_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_nms_mat_data10_write),
    .if_dout(nms_mat_data_dout),
    .if_num_data_valid(nms_mat_data_num_data_valid),
    .if_fifo_cap(nms_mat_data_fifo_cap),
    .if_empty_n(nms_mat_data_empty_n),
    .if_read(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_nms_mat_data10_read)
);

canny_accel_fifo_w16_d2_S img_height_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_height_c_din),
    .if_full_n(img_height_c_full_n),
    .if_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_height_c_write),
    .if_dout(img_height_c_dout),
    .if_num_data_valid(img_height_c_num_data_valid),
    .if_fifo_cap(img_height_c_fifo_cap),
    .if_empty_n(img_height_c_empty_n),
    .if_read(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_imgheight_read)
);

canny_accel_fifo_w16_d2_S img_width_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_width_c_din),
    .if_full_n(img_width_c_full_n),
    .if_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_img_width_c_write),
    .if_dout(img_width_c_dout),
    .if_num_data_valid(img_width_c_num_data_valid),
    .if_fifo_cap(img_width_c_fifo_cap),
    .if_empty_n(img_width_c_empty_n),
    .if_read(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_imgwidth_read)
);

canny_accel_start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0 start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_din),
    .if_full_n(start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_full_n),
    .if_write(entry_proc16_U0_start_write),
    .if_dout(start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_dout),
    .if_empty_n(start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_empty_n),
    .if_read(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_ready)
);

canny_accel_start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0 start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_din),
    .if_full_n(start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_full_n),
    .if_write(xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_start_write),
    .if_dout(start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_dout),
    .if_empty_n(start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_empty_n),
    .if_read(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_ready)
);

canny_accel_start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0 start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_din),
    .if_full_n(start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_full_n),
    .if_write(xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_start_write),
    .if_dout(start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_dout),
    .if_empty_n(start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_empty_n),
    .if_read(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_ready)
);

canny_accel_start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0 start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_din),
    .if_full_n(start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_full_n),
    .if_write(xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_start_write),
    .if_dout(start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_dout),
    .if_empty_n(start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_empty_n),
    .if_read(xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_ready)
);

canny_accel_start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0 start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_din),
    .if_full_n(start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_full_n),
    .if_write(xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_start_write),
    .if_dout(start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dout),
    .if_empty_n(start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_empty_n),
    .if_read(xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_height <= 1'b0;
    end else begin
        if (((xFCannyKernel_Block_entry15_proc_U0_ap_done & xFCannyKernel_Block_entry15_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_height <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_height <= ap_sync_channel_write_height;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_channel_write_imgwidth <= 1'b0;
    end else begin
        if (((xFCannyKernel_Block_entry15_proc_U0_ap_done & xFCannyKernel_Block_entry15_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_imgwidth <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_imgwidth <= ap_sync_channel_write_imgwidth;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_entry_proc16_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc16_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc16_U0_ap_ready <= ap_sync_entry_proc16_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready <= ap_sync_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_xFCannyKernel_Block_entry15_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_xFCannyKernel_Block_entry15_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_xFCannyKernel_Block_entry15_proc_U0_ap_ready <= ap_sync_xFCannyKernel_Block_entry15_proc_U0_ap_ready;
        end
    end
end

assign ap_channel_done_height = (xFCannyKernel_Block_entry15_proc_U0_ap_done & (ap_sync_reg_channel_write_height ^ 1'b1));

assign ap_channel_done_imgwidth = (xFCannyKernel_Block_entry15_proc_U0_ap_done & (ap_sync_reg_channel_write_imgwidth ^ 1'b1));

assign ap_done = xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_ext_blocking_sub_n = (xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_ext_blocking_n & xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_ext_blocking_n & xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_ext_blocking_n & xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_ext_blocking_n & xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_ext_blocking_n & xFCannyKernel_Block_entry15_proc_U0_ap_ext_blocking_n & xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ext_blocking_n & xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_ext_blocking_n & entry_proc16_U0_ap_ext_blocking_n);

assign ap_idle = (xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_idle & xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_idle & xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_idle & xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_idle & xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_idle & xFCannyKernel_Block_entry15_proc_U0_ap_idle & xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_idle & xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_idle & (height_empty_n ^ 1'b1) & (imgwidth_empty_n ^ 1'b1) & entry_proc16_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_int_blocking_sub_n = (xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_int_blocking_n & xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_int_blocking_n & xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_int_blocking_n & xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_int_blocking_n & xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_int_blocking_n & xFCannyKernel_Block_entry15_proc_U0_ap_int_blocking_n & xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_int_blocking_n & xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_int_blocking_n & entry_proc16_U0_ap_int_blocking_n);

assign ap_ready = ap_sync_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & ap_str_blocking_cur_n);

assign ap_str_blocking_sub_n = (xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_str_blocking_n & xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_str_blocking_n & xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_str_blocking_n & xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_str_blocking_n & xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_str_blocking_n & xFCannyKernel_Block_entry15_proc_U0_ap_str_blocking_n & xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_str_blocking_n & xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_str_blocking_n & entry_proc16_U0_ap_str_blocking_n);

assign ap_sync_channel_write_height = ((height_full_n & ap_channel_done_height) | ap_sync_reg_channel_write_height);

assign ap_sync_channel_write_imgwidth = ((imgwidth_full_n & ap_channel_done_imgwidth) | ap_sync_reg_channel_write_imgwidth);

assign ap_sync_entry_proc16_U0_ap_ready = (entry_proc16_U0_ap_ready | ap_sync_reg_entry_proc16_U0_ap_ready);

assign ap_sync_ready = (ap_sync_xFCannyKernel_Block_entry15_proc_U0_ap_ready & ap_sync_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready & ap_sync_entry_proc16_U0_ap_ready);

assign ap_sync_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready = (xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready | ap_sync_reg_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready);

assign ap_sync_xFCannyKernel_Block_entry15_proc_U0_ap_ready = (xFCannyKernel_Block_entry15_proc_U0_ap_ready | ap_sync_reg_xFCannyKernel_Block_entry15_proc_U0_ap_ready);

assign dst_mat_data2_din = xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dst_mat_data2_din;

assign dst_mat_data2_write = xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_dst_mat_data2_write;

assign entry_proc16_U0_ap_continue = 1'b1;

assign entry_proc16_U0_ap_start = ((ap_sync_reg_entry_proc16_U0_ap_ready ^ 1'b1) & ap_start);

assign in_mat_data1_read = xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_in_mat_data1_read;

assign start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_din = 1'b1;

assign start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_din = 1'b1;

assign start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_din = 1'b1;

assign start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_din = 1'b1;

assign start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_din = 1'b1;

assign xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_continue = 1'b1;

assign xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_ap_start = start_for_xFAngleKernel_2_0_1080_1920_3_0_1_2_2_5_1_1920_5760_U0_empty_n;

assign xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_continue = 1'b1;

assign xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_start = ((ap_sync_reg_xFAverageGaussianMask3x3_0_0_1080_1920_0_1_2_2_1_1920_U0_ap_ready ^ 1'b1) & ap_start);

assign xFCannyKernel_Block_entry15_proc_U0_ap_continue = (ap_sync_channel_write_imgwidth & ap_sync_channel_write_height);

assign xFCannyKernel_Block_entry15_proc_U0_ap_start = ((ap_sync_reg_xFCannyKernel_Block_entry15_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_continue = 1'b1;

assign xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_ap_start = start_for_xFDuplicate_rows_2_1080_1920_3_1_2_2_2_2_2_2_5_1920_U0_empty_n;

assign xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_continue = 1'b1;

assign xFMagnitudeKernel_2_2_1080_1920_3_3_1_2_2_2_5_5_1920_U0_ap_start = (imgwidth_empty_n & height_empty_n);

assign xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_continue = ap_continue;

assign xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_ap_start = start_for_xFPackNMS_8_8_1080_1920_12_12_1_32_2_2_0_20_U0_empty_n;

assign xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_continue = 1'b1;

assign xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_ap_start = start_for_xFSobel_0_2_1080_1920_0_3_1_2_2_2_1_5_3_false_U0_empty_n;

assign xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_continue = 1'b1;

assign xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_ap_start = start_for_xFSuppression3x3_2_0_8_1080_1920_3_0_12_1_2_5_1_0_1920_5760_2_U0_empty_n;

endmodule //canny_accel_xFCannyKernel
