// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sobel_accel_xFSobelFilter3x3_0_0_2160_3840_1_0_0_1_2_2_2_1_1_3840_false_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        in_mat_data1_dout,
        in_mat_data1_num_data_valid,
        in_mat_data1_fifo_cap,
        in_mat_data1_empty_n,
        in_mat_data1_read,
        p_dstgx_data2_din,
        p_dstgx_data2_num_data_valid,
        p_dstgx_data2_fifo_cap,
        p_dstgx_data2_full_n,
        p_dstgx_data2_write,
        p_dstgy_data3_din,
        p_dstgy_data3_num_data_valid,
        p_dstgy_data3_fifo_cap,
        p_dstgy_data3_full_n,
        p_dstgy_data3_write,
        img_height,
        img_width
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] in_mat_data1_dout;
input  [1:0] in_mat_data1_num_data_valid;
input  [1:0] in_mat_data1_fifo_cap;
input   in_mat_data1_empty_n;
output   in_mat_data1_read;
output  [7:0] p_dstgx_data2_din;
input  [1:0] p_dstgx_data2_num_data_valid;
input  [1:0] p_dstgx_data2_fifo_cap;
input   p_dstgx_data2_full_n;
output   p_dstgx_data2_write;
output  [7:0] p_dstgy_data3_din;
input  [1:0] p_dstgy_data3_num_data_valid;
input  [1:0] p_dstgy_data3_fifo_cap;
input   p_dstgy_data3_full_n;
output   p_dstgy_data3_write;
input  [15:0] img_height;
input  [15:0] img_width;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_mat_data1_read;
reg[7:0] p_dstgx_data2_din;
reg p_dstgx_data2_write;
reg[7:0] p_dstgy_data3_din;
reg p_dstgy_data3_write;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_dstgx_data2_blk_n;
wire    ap_CS_fsm_state7;
reg    p_dstgy_data3_blk_n;
wire   [1:0] bottom_V_fu_278_p3;
reg   [1:0] bottom_V_reg_510;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln1027_fu_225_p2;
wire   [1:0] mid_V_fu_309_p3;
reg   [1:0] mid_V_reg_515;
wire   [1:0] tp_V_fu_340_p3;
reg   [1:0] tp_V_reg_520;
wire   [0:0] cmp_i_i603_i_fu_349_p2;
reg   [0:0] cmp_i_i603_i_reg_525;
wire   [1:0] empty_52_fu_355_p1;
reg   [1:0] empty_52_reg_530;
reg    buf_V_ce0;
wire   [7:0] buf_V_q0;
reg   [11:0] buf_V_address1;
reg    buf_V_ce1;
reg    buf_V_we1;
reg   [7:0] buf_V_d1;
reg    buf_V_1_ce0;
wire   [7:0] buf_V_1_q0;
reg   [11:0] buf_V_1_address1;
reg    buf_V_1_ce1;
reg    buf_V_1_we1;
reg   [7:0] buf_V_1_d1;
wire   [7:0] buf_V_2_q0;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_idle;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_ready;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_in_mat_data1_read;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_d1;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_d1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_idle;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_ready;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_in_mat_data1_read;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgx_data2_din;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgx_data2_write;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgy_data3_din;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgy_data3_write;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce0;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_d1;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce0;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_d1;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address0;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce0;
wire   [11:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce1;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_we1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_d1;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out_ap_vld;
wire   [7:0] grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out;
wire    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out_ap_vld;
wire    ref_tmp_xFGradientX3x3_0_0_s_fu_181_ap_ready;
wire   [7:0] ref_tmp_xFGradientX3x3_0_0_s_fu_181_ap_return;
wire    ref_tmp1_xFGradientY3x3_0_0_s_fu_195_ap_ready;
wire   [7:0] ref_tmp1_xFGradientY3x3_0_0_s_fu_195_ap_return;
reg    grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state3;
reg    grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [12:0] row_ind_V_fu_70;
wire   [12:0] row_ind_V_2_fu_372_p3;
reg   [12:0] row_V_fu_74;
wire   [12:0] row_V_3_fu_380_p2;
reg   [1:0] tp_fu_78;
reg   [1:0] mid_fu_82;
reg   [1:0] bottom_fu_86;
reg    ap_block_state7;
wire   [15:0] zext_ln1027_fu_221_p1;
wire   [0:0] icmp_ln370_fu_242_p2;
wire   [0:0] icmp_ln370_2_fu_262_p2;
wire   [0:0] icmp_ln370_1_fu_256_p2;
wire   [0:0] empty_47_fu_272_p2;
wire   [1:0] empty_46_fu_268_p1;
wire   [1:0] select_ln370_fu_248_p3;
wire   [0:0] empty_49_fu_303_p2;
wire   [1:0] empty_48_fu_295_p3;
wire   [1:0] select_ln370_1_fu_287_p3;
wire   [0:0] empty_51_fu_334_p2;
wire   [1:0] empty_50_fu_326_p3;
wire   [1:0] select_ln370_2_fu_318_p3;
wire   [12:0] row_ind_V_1_fu_360_p2;
wire   [0:0] icmp_ln1019_fu_366_p2;
reg   [6:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg = 1'b0;
#0 grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg = 1'b0;
end

sobel_accel_xFSobelFilter3x3_0_0_2160_3840_1_0_0_1_2_2_2_1_1_3840_false_s_buf_V_RAM_S2P_Bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
buf_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address0),
    .ce0(buf_V_ce0),
    .q0(buf_V_q0),
    .address1(buf_V_address1),
    .ce1(buf_V_ce1),
    .we1(buf_V_we1),
    .d1(buf_V_d1)
);

sobel_accel_xFSobelFilter3x3_0_0_2160_3840_1_0_0_1_2_2_2_1_1_3840_false_s_buf_V_RAM_S2P_Bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
buf_V_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address0),
    .ce0(buf_V_1_ce0),
    .q0(buf_V_1_q0),
    .address1(buf_V_1_address1),
    .ce1(buf_V_1_ce1),
    .we1(buf_V_1_we1),
    .d1(buf_V_1_d1)
);

sobel_accel_xFSobelFilter3x3_0_0_2160_3840_1_0_0_1_2_2_2_1_1_3840_false_s_buf_V_RAM_S2P_Bbkb #(
    .DataWidth( 8 ),
    .AddressRange( 3840 ),
    .AddressWidth( 12 ))
buf_V_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address0),
    .ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce0),
    .q0(buf_V_2_q0),
    .address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address1),
    .ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce1),
    .we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_we1),
    .d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_d1)
);

sobel_accel_xFSobelFilter3x3_Pipeline_Clear_Row_Loop grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start),
    .ap_done(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_ready),
    .in_mat_data1_dout(in_mat_data1_dout),
    .in_mat_data1_num_data_valid(2'd0),
    .in_mat_data1_fifo_cap(2'd0),
    .in_mat_data1_empty_n(in_mat_data1_empty_n),
    .in_mat_data1_read(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_in_mat_data1_read),
    .img_width(img_width),
    .buf_V_1_address1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_address1),
    .buf_V_1_ce1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_ce1),
    .buf_V_1_we1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_we1),
    .buf_V_1_d1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_d1),
    .buf_V_address1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_address1),
    .buf_V_ce1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_ce1),
    .buf_V_we1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_we1),
    .buf_V_d1(grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_d1)
);

sobel_accel_xFSobelFilter3x3_Pipeline_Col_Loop grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start),
    .ap_done(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done),
    .ap_idle(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_idle),
    .ap_ready(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_ready),
    .in_mat_data1_dout(in_mat_data1_dout),
    .in_mat_data1_num_data_valid(2'd0),
    .in_mat_data1_fifo_cap(2'd0),
    .in_mat_data1_empty_n(in_mat_data1_empty_n),
    .in_mat_data1_read(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_in_mat_data1_read),
    .p_dstgx_data2_din(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgx_data2_din),
    .p_dstgx_data2_num_data_valid(2'd0),
    .p_dstgx_data2_fifo_cap(2'd0),
    .p_dstgx_data2_full_n(p_dstgx_data2_full_n),
    .p_dstgx_data2_write(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgx_data2_write),
    .p_dstgy_data3_din(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgy_data3_din),
    .p_dstgy_data3_num_data_valid(2'd0),
    .p_dstgy_data3_fifo_cap(2'd0),
    .p_dstgy_data3_full_n(p_dstgy_data3_full_n),
    .p_dstgy_data3_write(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgy_data3_write),
    .img_width(img_width),
    .tp_V(tp_V_reg_520),
    .mid_V(mid_V_reg_515),
    .bottom_V(bottom_V_reg_510),
    .row_ind_V_cast(empty_52_reg_530),
    .buf_V_2_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address0),
    .buf_V_2_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce0),
    .buf_V_2_q0(buf_V_2_q0),
    .buf_V_2_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_address1),
    .buf_V_2_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_ce1),
    .buf_V_2_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_we1),
    .buf_V_2_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_2_d1),
    .buf_V_1_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address0),
    .buf_V_1_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce0),
    .buf_V_1_q0(buf_V_1_q0),
    .buf_V_1_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address1),
    .buf_V_1_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce1),
    .buf_V_1_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_we1),
    .buf_V_1_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_d1),
    .buf_V_address0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address0),
    .buf_V_ce0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce0),
    .buf_V_q0(buf_V_q0),
    .buf_V_address1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address1),
    .buf_V_ce1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce1),
    .buf_V_we1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_we1),
    .buf_V_d1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_d1),
    .cmp_i_i603_i(cmp_i_i603_i_reg_525),
    .src_buf3_V_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out),
    .src_buf3_V_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out_ap_vld),
    .p_Val2_2_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out),
    .p_Val2_2_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out_ap_vld),
    .p_Val2_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out),
    .p_Val2_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out_ap_vld),
    .src_buf1_V_1_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out),
    .src_buf1_V_1_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out_ap_vld),
    .p_Val2_out(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out),
    .p_Val2_out_ap_vld(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out_ap_vld)
);

sobel_accel_xFGradientX3x3_0_0_s ref_tmp_xFGradientX3x3_0_0_s_fu_181(
    .ap_ready(ref_tmp_xFGradientX3x3_0_0_s_fu_181_ap_ready),
    .t0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out),
    .t2(8'd0),
    .m0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_1_out),
    .m2(8'd0),
    .b0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out),
    .b2(8'd0),
    .ap_return(ref_tmp_xFGradientX3x3_0_0_s_fu_181_ap_return)
);

sobel_accel_xFGradientY3x3_0_0_s ref_tmp1_xFGradientY3x3_0_0_s_fu_195(
    .ap_ready(ref_tmp1_xFGradientY3x3_0_0_s_fu_195_ap_ready),
    .t0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_out),
    .t1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf1_V_1_out),
    .t2(8'd0),
    .b0(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_Val2_2_out),
    .b1(grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_src_buf3_V_1_out),
    .b2(8'd0),
    .ap_return(ref_tmp1_xFGradientY3x3_0_0_s_fu_195_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln1027_fu_225_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b1;
        end else if ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_ready == 1'b1)) begin
            grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_V_fu_74 <= 13'd1;
    end else if (((icmp_ln1027_fu_225_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        row_V_fu_74 <= row_V_3_fu_380_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_ind_V_fu_70 <= 13'd2;
    end else if (((icmp_ln1027_fu_225_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        row_ind_V_fu_70 <= row_ind_V_2_fu_372_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1027_fu_225_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        bottom_V_reg_510 <= bottom_V_fu_278_p3;
        bottom_fu_86 <= bottom_V_fu_278_p3;
        cmp_i_i603_i_reg_525 <= cmp_i_i603_i_fu_349_p2;
        empty_52_reg_530 <= empty_52_fu_355_p1;
        mid_V_reg_515 <= mid_V_fu_309_p3;
        mid_fu_82 <= mid_V_fu_309_p3;
        tp_V_reg_520 <= tp_V_fu_340_p3;
        tp_fu_78 <= tp_V_fu_340_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if (((p_dstgy_data3_full_n == 1'b0) | (p_dstgx_data2_full_n == 1'b0))) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln1027_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln1027_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_address1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_address1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_address1;
    end else begin
        buf_V_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_ce0 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce0;
    end else begin
        buf_V_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_ce1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_ce1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_ce1;
    end else begin
        buf_V_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_d1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_d1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_d1;
    end else begin
        buf_V_1_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_1_we1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_1_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_1_we1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_1_we1;
    end else begin
        buf_V_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_address1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_address1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_address1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_address1;
    end else begin
        buf_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_ce0 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce0;
    end else begin
        buf_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_ce1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_ce1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_ce1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_ce1;
    end else begin
        buf_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_d1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_d1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_d1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_d1;
    end else begin
        buf_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_V_we1 = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_buf_V_we1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        buf_V_we1 = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_buf_V_we1;
    end else begin
        buf_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        in_mat_data1_read = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_in_mat_data1_read;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        in_mat_data1_read = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_in_mat_data1_read;
    end else begin
        in_mat_data1_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_dstgx_data2_blk_n = p_dstgx_data2_full_n;
    end else begin
        p_dstgx_data2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_dstgy_data3_full_n == 1'b0) | (p_dstgx_data2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        p_dstgx_data2_din = ref_tmp_xFGradientX3x3_0_0_s_fu_181_ap_return;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_dstgx_data2_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgx_data2_din;
    end else begin
        p_dstgx_data2_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgx_data2_din;
    end
end

always @ (*) begin
    if ((~((p_dstgy_data3_full_n == 1'b0) | (p_dstgx_data2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        p_dstgx_data2_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_dstgx_data2_write = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgx_data2_write;
    end else begin
        p_dstgx_data2_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        p_dstgy_data3_blk_n = p_dstgy_data3_full_n;
    end else begin
        p_dstgy_data3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_dstgy_data3_full_n == 1'b0) | (p_dstgx_data2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        p_dstgy_data3_din = ref_tmp1_xFGradientY3x3_0_0_s_fu_195_ap_return;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_dstgy_data3_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgy_data3_din;
    end else begin
        p_dstgy_data3_din = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgy_data3_din;
    end
end

always @ (*) begin
    if ((~((p_dstgy_data3_full_n == 1'b0) | (p_dstgx_data2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
        p_dstgy_data3_write = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        p_dstgy_data3_write = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_p_dstgy_data3_write;
    end else begin
        p_dstgy_data3_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln1027_fu_225_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if ((~((p_dstgy_data3_full_n == 1'b0) | (p_dstgx_data2_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state7 = ((p_dstgy_data3_full_n == 1'b0) | (p_dstgx_data2_full_n == 1'b0));
end

assign bottom_V_fu_278_p3 = ((empty_47_fu_272_p2[0:0] == 1'b1) ? empty_46_fu_268_p1 : select_ln370_fu_248_p3);

assign cmp_i_i603_i_fu_349_p2 = ((zext_ln1027_fu_221_p1 < img_height) ? 1'b1 : 1'b0);

assign empty_46_fu_268_p1 = icmp_ln370_2_fu_262_p2;

assign empty_47_fu_272_p2 = (icmp_ln370_2_fu_262_p2 | icmp_ln370_1_fu_256_p2);

assign empty_48_fu_295_p3 = ((icmp_ln370_2_fu_262_p2[0:0] == 1'b1) ? 2'd0 : 2'd2);

assign empty_49_fu_303_p2 = (icmp_ln370_2_fu_262_p2 | icmp_ln370_1_fu_256_p2);

assign empty_50_fu_326_p3 = ((icmp_ln370_2_fu_262_p2[0:0] == 1'b1) ? 2'd2 : 2'd1);

assign empty_51_fu_334_p2 = (icmp_ln370_2_fu_262_p2 | icmp_ln370_1_fu_256_p2);

assign empty_52_fu_355_p1 = row_ind_V_fu_70[1:0];

assign grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start = grp_xFSobelFilter3x3_Pipeline_Clear_Row_Loop_fu_148_ap_start_reg;

assign grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start = grp_xFSobelFilter3x3_Pipeline_Col_Loop_fu_157_ap_start_reg;

assign icmp_ln1019_fu_366_p2 = ((row_ind_V_1_fu_360_p2 == 13'd3) ? 1'b1 : 1'b0);

assign icmp_ln1027_fu_225_p2 = ((zext_ln1027_fu_221_p1 > img_height) ? 1'b1 : 1'b0);

assign icmp_ln370_1_fu_256_p2 = ((row_ind_V_fu_70 == 13'd0) ? 1'b1 : 1'b0);

assign icmp_ln370_2_fu_262_p2 = ((row_ind_V_fu_70 == 13'd1) ? 1'b1 : 1'b0);

assign icmp_ln370_fu_242_p2 = ((row_ind_V_fu_70 == 13'd2) ? 1'b1 : 1'b0);

assign mid_V_fu_309_p3 = ((empty_49_fu_303_p2[0:0] == 1'b1) ? empty_48_fu_295_p3 : select_ln370_1_fu_287_p3);

assign row_V_3_fu_380_p2 = (row_V_fu_74 + 13'd1);

assign row_ind_V_1_fu_360_p2 = (row_ind_V_fu_70 + 13'd1);

assign row_ind_V_2_fu_372_p3 = ((icmp_ln1019_fu_366_p2[0:0] == 1'b1) ? 13'd0 : row_ind_V_1_fu_360_p2);

assign select_ln370_1_fu_287_p3 = ((icmp_ln370_fu_242_p2[0:0] == 1'b1) ? 2'd1 : mid_fu_82);

assign select_ln370_2_fu_318_p3 = ((icmp_ln370_fu_242_p2[0:0] == 1'b1) ? 2'd0 : tp_fu_78);

assign select_ln370_fu_248_p3 = ((icmp_ln370_fu_242_p2[0:0] == 1'b1) ? 2'd2 : bottom_fu_86);

assign tp_V_fu_340_p3 = ((empty_51_fu_334_p2[0:0] == 1'b1) ? empty_50_fu_326_p3 : select_ln370_2_fu_318_p3);

assign zext_ln1027_fu_221_p1 = row_V_fu_74;

endmodule //sobel_accel_xFSobelFilter3x3_0_0_2160_3840_1_0_0_1_2_2_2_1_1_3840_false_s
