# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.runs/synth_1/vitis_design_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param project.enablePRFlowIPI 1
set_param bd.debug_profile.script /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/.local/debug_profile_automation.tcl
set_param bd.enable_dpa 1
set_param project.loadTopLevelOOCConstrs 1
set_param project.gatelevelSubdesign 1
set_param place.ultrathreadsUsed 0
set_param hd.Visual 0
set_param general.maxThreads 1
set_param bd.ForceAppCoreUpgrade 1
set_param compiler.enablePerformanceTrace 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.cache/wt [current_project]
set_property parent.project_path /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/.local/hw_platform/board} [current_project]
set_property board_part xilinx.com:zcu102:part0:3.4 [current_project]
set_property ip_repo_paths {
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_image_thresholding_kernel01_1_0
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_image_thresholding_kernel00_1_0
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_gaussian_filter_accel_1_0
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_remap_accel_1_0
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_canny_accel_1_0
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_threshold_accel_1_0
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_fast_accel_1_0
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_sobel_accel_1_0
  /tools/Xilinx/Vitis/2022.2/data/cache/xilinx
  /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/.local/hw_platform/ipcache
  /tools/Xilinx/Vitis/2022.2/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/.ipcache [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/hdl/vitis_design_wrapper.v
add_files /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/vitis_design/vitis_design.bd
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_0_0/vitis_design_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_0_0/vitis_design_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_intc_0_0/vitis_design_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_register_slice_0_0/vitis_design_axi_register_slice_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_register_slice_0_0/vitis_design_axi_register_slice_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_vip_0_0/vitis_design_axi_vip_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_axi_vip_1_0/vitis_design_axi_vip_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_clk_wiz_0_0/vitis_design_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_clk_wiz_0_0/vitis_design_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_clk_wiz_0_0/vitis_design_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_0_0/vitis_design_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_0_0/vitis_design_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_0_0/vitis_design_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_1_0/vitis_design_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_1_0/vitis_design_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_1_0/vitis_design_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_2_0/vitis_design_proc_sys_reset_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_2_0/vitis_design_proc_sys_reset_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_2_0/vitis_design_proc_sys_reset_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_3_0/vitis_design_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_3_0/vitis_design_proc_sys_reset_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_3_0/vitis_design_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_4_0/vitis_design_proc_sys_reset_4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_4_0/vitis_design_proc_sys_reset_4_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_4_0/vitis_design_proc_sys_reset_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_5_0/vitis_design_proc_sys_reset_5_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_5_0/vitis_design_proc_sys_reset_5_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_5_0/vitis_design_proc_sys_reset_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_6_0/vitis_design_proc_sys_reset_6_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_6_0/vitis_design_proc_sys_reset_6_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_proc_sys_reset_6_0/vitis_design_proc_sys_reset_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_ps_e_0/vitis_design_ps_e_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_ps_e_0/vitis_design_ps_e_0.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_xbar_0/vitis_design_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_remap_accel_1_0/constraints/remap_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_canny_accel_1_0/constraints/canny_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_sobel_accel_1_0/constraints/sobel_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_threshold_accel_1_0/constraints/threshold_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_gaussian_filter_accel_1_0/constraints/gaussian_filter_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_image_thresholding_kernel00_1_0/constraints/image_thresholding_kernel00_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_image_thresholding_kernel01_1_0/constraints/image_thresholding_kernel01_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_fast_accel_1_0/constraints/fast_accel_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_xbar_1/vitis_design_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_xbar_2/vitis_design_xbar_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_0/vitis_design_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_0/vitis_design_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_0/vitis_design_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_pc_0/vitis_design_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m01_regslice_0/vitis_design_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m01_regslice_0/vitis_design_m01_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_0/vitis_design_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_0/vitis_design_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_0/vitis_design_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m02_regslice_0/vitis_design_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m02_regslice_0/vitis_design_m02_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_1/vitis_design_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_1/vitis_design_auto_cc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_1/vitis_design_auto_cc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m03_regslice_0/vitis_design_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m03_regslice_0/vitis_design_m03_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_2/vitis_design_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_2/vitis_design_auto_cc_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_2/vitis_design_auto_cc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m04_regslice_0/vitis_design_m04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m04_regslice_0/vitis_design_m04_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_3/vitis_design_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_3/vitis_design_auto_cc_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_3/vitis_design_auto_cc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m05_regslice_0/vitis_design_m05_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m05_regslice_0/vitis_design_m05_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_4/vitis_design_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_4/vitis_design_auto_cc_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_4/vitis_design_auto_cc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m06_regslice_0/vitis_design_m06_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m06_regslice_0/vitis_design_m06_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_5/vitis_design_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_5/vitis_design_auto_cc_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_5/vitis_design_auto_cc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m07_regslice_0/vitis_design_m07_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m07_regslice_0/vitis_design_m07_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_6/vitis_design_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_6/vitis_design_auto_cc_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_6/vitis_design_auto_cc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m08_regslice_0/vitis_design_m08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m08_regslice_0/vitis_design_m08_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_7/vitis_design_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_7/vitis_design_auto_cc_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_cc_7/vitis_design_auto_cc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s00_regslice_2/vitis_design_s00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s00_regslice_2/vitis_design_s00_regslice_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_0/vitis_design_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_0/vitis_design_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_0/vitis_design_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s01_regslice_2/vitis_design_s01_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s01_regslice_2/vitis_design_s01_regslice_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_1/vitis_design_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_1/vitis_design_auto_us_df_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_1/vitis_design_auto_us_df_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s02_regslice_0/vitis_design_s02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s02_regslice_0/vitis_design_s02_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_2/vitis_design_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_2/vitis_design_auto_us_df_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_2/vitis_design_auto_us_df_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s03_regslice_0/vitis_design_s03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s03_regslice_0/vitis_design_s03_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_3/vitis_design_auto_us_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_3/vitis_design_auto_us_df_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_3/vitis_design_auto_us_df_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s04_regslice_0/vitis_design_s04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s04_regslice_0/vitis_design_s04_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_4/vitis_design_auto_us_df_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_4/vitis_design_auto_us_df_4_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_4/vitis_design_auto_us_df_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s05_regslice_0/vitis_design_s05_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s05_regslice_0/vitis_design_s05_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_5/vitis_design_auto_us_df_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_5/vitis_design_auto_us_df_5_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_5/vitis_design_auto_us_df_5_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s06_regslice_0/vitis_design_s06_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s06_regslice_0/vitis_design_s06_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s06_data_fifo_0/vitis_design_s06_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s06_data_fifo_0/vitis_design_s06_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s06_data_fifo_0/vitis_design_s06_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s07_regslice_0/vitis_design_s07_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s07_regslice_0/vitis_design_s07_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s07_data_fifo_0/vitis_design_s07_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s07_data_fifo_0/vitis_design_s07_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s07_data_fifo_0/vitis_design_s07_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s08_regslice_0/vitis_design_s08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s08_regslice_0/vitis_design_s08_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s08_data_fifo_0/vitis_design_s08_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s08_data_fifo_0/vitis_design_s08_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s08_data_fifo_0/vitis_design_s08_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s09_regslice_0/vitis_design_s09_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s09_regslice_0/vitis_design_s09_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s09_data_fifo_0/vitis_design_s09_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s09_data_fifo_0/vitis_design_s09_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s09_data_fifo_0/vitis_design_s09_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s10_regslice_0/vitis_design_s10_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s10_regslice_0/vitis_design_s10_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s10_data_fifo_0/vitis_design_s10_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s10_data_fifo_0/vitis_design_s10_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s10_data_fifo_0/vitis_design_s10_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s11_regslice_0/vitis_design_s11_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s11_regslice_0/vitis_design_s11_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s11_data_fifo_0/vitis_design_s11_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s11_data_fifo_0/vitis_design_s11_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s11_data_fifo_0/vitis_design_s11_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s12_regslice_0/vitis_design_s12_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s12_regslice_0/vitis_design_s12_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s12_data_fifo_0/vitis_design_s12_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s12_data_fifo_0/vitis_design_s12_data_fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s12_data_fifo_0/vitis_design_s12_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s13_regslice_0/vitis_design_s13_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s13_regslice_0/vitis_design_s13_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_6/vitis_design_auto_us_df_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_6/vitis_design_auto_us_df_6_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_6/vitis_design_auto_us_df_6_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s14_regslice_0/vitis_design_s14_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s14_regslice_0/vitis_design_s14_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_7/vitis_design_auto_us_df_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_7/vitis_design_auto_us_df_7_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_7/vitis_design_auto_us_df_7_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s15_regslice_0/vitis_design_s15_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s15_regslice_0/vitis_design_s15_regslice_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_8/vitis_design_auto_us_df_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_8/vitis_design_auto_us_df_8_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_8/vitis_design_auto_us_df_8_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_data_fifo_2/vitis_design_m00_data_fifo_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_data_fifo_2/vitis_design_m00_data_fifo_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_data_fifo_2/vitis_design_m00_data_fifo_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_regslice_2/vitis_design_m00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_regslice_2/vitis_design_m00_regslice_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_ds_0/vitis_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_ds_0/vitis_design_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_ds_0/vitis_design_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s00_regslice_3/vitis_design_s00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s00_regslice_3/vitis_design_s00_regslice_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_9/vitis_design_auto_us_df_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_9/vitis_design_auto_us_df_9_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_9/vitis_design_auto_us_df_9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s01_regslice_3/vitis_design_s01_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_s01_regslice_3/vitis_design_s01_regslice_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_10/vitis_design_auto_us_df_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_10/vitis_design_auto_us_df_10_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_auto_us_df_10/vitis_design_auto_us_df_10_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_data_fifo_3/vitis_design_m00_data_fifo_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_data_fifo_3/vitis_design_m00_data_fifo_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_data_fifo_3/vitis_design_m00_data_fifo_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_regslice_3/vitis_design_m00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/ip/vitis_design_m00_regslice_3/vitis_design_m00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/vitis_design/vitis_design_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/output/vitis_design_ooc_copy.xdc
set_property used_in_implementation false [get_files /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/output/vitis_design_ooc_copy.xdc]
set_property processing_order EARLY [get_files /home/overman/dev/workspaces/vision/vision_system_hw_link/Hardware/binary_container_1.build/link/vivado/vpl/output/vitis_design_ooc_copy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top vitis_design_wrapper -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vitis_design_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
